---
backend:
  bucket: "my-terraform-state"
  key: "my-terraform-state"
  region: "us-east-1"
  dynamodb_table: "my-terraform-state-lock"
  profile: "my-terraform-state"
  workspace_key_prefix: "my-terraform-state"

presentation:
  s3_bucket: "my-terraform-state"
  s3_access_key: "Random access key"
